export type Action =
  | 'asymmetricDecrypt'
  | 'asymmetricEncrypt'
  | 'destroySession'
  | 'encryptPrivateKey'
  | 'exportSession'
  | 'generateIdentity'
  | 'generateKeyPair'
  | 'hybridDecrypt'
  | 'hybridEncrypt'
  | 'importKeyPair'
  | 'importSession'
  | 'hybridShareKey'
  | 'symmetricDecrypt'
  | 'symmetricEncrypt';
