name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

jobs:
  js-build:
    runs-on: ubuntu-latest
    name: JS / Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build:js

  js-lint:
    runs-on: ubuntu-latest
    name: JS / Lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint:js

  js-test:
    runs-on: ubuntu-latest
    name: JS / Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run test -w packages/js

  svelte-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        svelte-version: [^3.55.0, ^4.0.0]
    name: Svelte / Build / Svelte ${{ matrix.svelte-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm install -D svelte@${{ matrix.svelte-version }}
      - run: npm run build:js
      - run: npm run build:svelte

  svelte-5-build:
    runs-on: ubuntu-latest
    name: Svelte / Build / Svelte 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm install -D svelte@^5.0.0-next.0 --legacy-peer-deps
      - run: npm run build:js
      - run: npm run build:svelte

  svelte-lint:
    runs-on: ubuntu-latest
    name: Svelte / Lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build:js
      - run: npm run lint:svelte
